export const FETCH_SONGS_START = 'FETCH_SONGS_START';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_ERROR = 'FETCH_SONGS_ERROR';

export const SELECT_SONG_START = 'SELECT_SONG_START';
export const SELECT_SONG_SUCCESS = 'SELECT_SONG_SUCCESS';
export const SELECT_SONG_ERROR = 'SELECT_SONG_ERROR';

export const TOGGLE_PLAY_START = 'TOGGLE_PLAY_START';
export const TOGGLE_PLAY_SUCCESS = 'TOGGLE_PLAY_SUCCESS';
export const TOGGLE_PLAY_ERROR = 'TOGGLE_PLAY_ERROR';

export const FETCH_TIME_PROPERTIES_START = 'FETCH_TIME_PROPERTIES_START';
export const FETCH_TIME_PROPERTIES_SUCCESS = 'FETCH_TIME_PROPERTIES_SUCCESS';
export const FETCH_TIME_PROPERTIES_ERROR = 'FETCH_TIME_PROPERTIES_ERROR';
